In [3]:
!pip install pandas openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (2.2.3)
Requirement already satisfied: openpyxl in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (3.1.5)
Collecting sqlalchemy
  Using cached SQLAlchemy-2.0.36-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: numpy>=1.26.0 in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (from sqlalchemy) (4.12.2)
Collecting greenlet!=0.4.17 (from sqlalchemy)
  Using cached greenlet-3.1.1-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: six>=1.5 in d:\constructal_automate_post_processing\constructal-automate-pp-venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Using cached SQLAlchemy-2.0.36-cp312-cp312-win_amd64.whl (2.1 MB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Using cached greenlet-3.1.1-cp312-cp312-win_amd64.whl (299 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy
Successfully installed greenlet-3.1.1 pymysql-1.1.1 sqlalchemy-2.0.36

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from sqlalchemy import create_engine
import pandas as pd

# Conexão com o MariaDB
db_user = 'constructal_automate'
db_password = 'constructal_design_2024'
db_host = 'localhost'
db_name = 'constructal_automate_results'
engine = create_engine(f'mysql+pymysql://{db_user}:{db_password}@{db_host}/{db_name}')

# Leia a planilha Excel
#E:\Backups\2024 - BKP PC Dexian\Estudos\Estudos\Mestrado\Defesa Final\resultados
file_path = 'E:/Backups/2024 - BKP PC Dexian/Estudos/Estudos/Mestrado/Defesa Final/resultados/geometria_enrijecedores.xlsx'

df_plate = pd.read_excel(file_path, sheet_name='csg_plate')
df_stiffened_plate = pd.read_excel(file_path, sheet_name='csg_stiffenedplate')

In [7]:
df_plate

   id     a     b  t_0
0   1  2000  1000   14

In [8]:
df_stiffened_plate

,id,phi,N_ls,N_ts,k,t_1,h_s,t_s,description,plate_id
0,1,0.0,0,0,0.000,14.0,0,0,EC - Comparação com Lima et al. (2020),1
1,2,0.3,2,2,56.200,9.8,281,5,EC - Comparação com Lima et al. (2020),1
2,3,0.3,2,2,14.100,9.8,141,10,EC - Comparação com Lima et al. (2020),1
3,4,0.3,2,2,6.333,9.8,95,15,EC - Comparação com Lima et al. (2020),1
4,5,0.3,2,2,3.550,9.8,71,20,EC - Comparação com Lima et al. (2020),1
...,...,...,...,...,...,...,...,...,...,...
124,125,0.3,5,5,1.450,9.8,29,20,EC - Comparação com Lima et al. (2020),1
125,126,0.3,5,5,0.960,9.8,24,25,EC - Comparação com Lima et al. (2020),1
126,127,0.3,5,5,0.666,9.8,20,30,EC - Comparação com Lima et al. (2020),1
127,128,0.3,5,5,0.485,9.8,17,35,EC - Comparação com Lima et al. (2020),1
128,129,0.3,5,5,0.375,9.8,15,40,EC - Comparação com Lima et al. (2020),1

In [11]:
df_plate.to_sql('csg_plate', con=engine, if_exists='append', index=False)

1

In [12]:
df_stiffened_plate.to_sql('csg_stiffenedplate', con=engine, if_exists='append', index=False)

129